export const products = [
  {
    id: 1,
    title: 'React Handbook',
    category: 'Books',
    rating: 4.8,
    description: 'یک کتاب نمونه برای تمرین نمایش داده‌ها در React.',
    price: 29,
    stock: 12,
    emoji: '📘',
  },
  {
    id: 2,
    title: 'Mechanical Keyboard',
    category: 'Electronics',
    rating: 4.6,
    description: 'کیبورد مکانیکی نمونه برای کارت محصولات.',
    price: 89,
    stock: 7,
    emoji: '⌨️',
  },
  {
    id: 3,
    title: 'Wireless Mouse',
    category: 'Accessories',
    rating: 4.4,
    description: 'ماوس بی‌سیم سبک برای استفاده روزمره.',
    price: 34,
    stock: 15,
    emoji: '🖱️',
  },
  {
    id: 4,
    title: '4K Monitor',
    category: 'Electronics',
    rating: 4.9,
    description: 'مانیتور نمونه برای تمرین فیلتر و جست‌وجو.',
    price: 399,
    stock: 3,
    emoji: '🖥️',
  },
  {
    id: 5,
    title: 'Desk Lamp',
    category: 'Office',
    rating: 4.2,
    description: 'چراغ رومیزی ساده برای فضای کار.',
    price: 45,
    stock: 0,
    emoji: '💡',
  },
  {
    id: 6,
    title: 'USB-C Hub',
    category: 'Accessories',
    rating: 4.5,
    description: 'هاب USB-C چندکاره برای لپ‌تاپ.',
    price: 59,
    stock: 9,
    emoji: '🔌',
  },
  {
    id: 7,
    title: 'Notebook',
    category: 'Office',
    rating: 4.1,
    description: 'دفتر یادداشت برای تمرین نمایش اطلاعات.',
    price: 12,
    stock: 30,
    emoji: '📓',
  },
  {
    id: 8,
    title: 'Headphones',
    category: 'Electronics',
    rating: 4.7,
    description: 'هدفون نمونه برای تکمیل گرید محصولات.',
    price: 129,
    stock: 5,
    emoji: '🎧',
  },
]
